### ISSUE TITLE
Improve counter using fingerprint instead ip address

### ISSUE THREAD

**Issue by siimaoo** [alt-art/github-counter#1]
Users in same network or in same region using same internet provider can have same ip address (It's an edge case but it can happen).
I think using fingerprint will be better than IP.

[More about fingerprint](https://w3c.github.io/fingerprinting-guidance/#what-is-fingerprinting)

**Comment by alt-art** [comment]
I know this is possible, but I believe it is very unlikely that an IP will be the same as another within 48 hours, if you know how to implement it feel free to make a pull request.

First I need to solve another complex problem, recently I discovered that GitHub stores an SVG cache on its own server, which is very strange since in the other counters I tested this doesn't happen.

**Comment by alt-art** [comment]
I will try this, thank you.

Em ter., 18 de out. de 2022 às 17:45, Lucas Simão ***@***.***>
escreveu:
